name: Test the action

on:
    workflow_dispatch:
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Send a test webhook
              uses: ./
              with:
                  webhook-url: ${{ secrets.WEBHOOK_URL }}
                  debug-print: true
                  content: |
                      This is a test message
                      with multiple lines!

                      [Link to GitHub](<https://github.com>)
                  author: "Epic Webhook"
                  avatar: "https://i.imgur.com/vIVtTrU.png"
                  files: |
                      *.md
                      *.json
                  embed-title: "Test Embed"
                  embed-description: "This is a test embed."
                  embed-url: "https://github.com/BlueWitherer/discord-webhook" # sry prev </3
                  embed-author: "Some Author"
                  embed-author-icon: "https://i.imgur.com/vIVtTrU.png"
                  embed-color: "#FF7FED"
                  embed-fields: |
                      first=First field
                      second=Second field
                      third=Third field
                      fourth=Fourth field
                  embed-image: "https://i.imgur.com/vIVtTrU.png"
                  embed-thumbnail: "https://i.imgur.com/vIVtTrU.png"
                  embed-footer: "Test Footer"
                  embed-footer-icon: "https://i.imgur.com/vIVtTrU.png"
                  embed-timestamp: "now"
